Feature/auth updates
Do-Stuff-Club/expense_tracker_web pull request #33
Opened 2021-12-01 20:44 UTC by edward93

No more getting logged out when refreshing the page.
Created new httpClient to hide the implementation details and make transition to other package i.e. fetch api, much easier.

Other QOL changes

2021-12-01 21:17 UTC, kwf37 requested changes
- I like the new env file for declaring constants
- Love the new HttpClient module! It's great that it handles the authentication stuff internally and makes it easier to swap request libraries.
- Love the removal of all the redundant authHeader stuff!
Overall looks great- I added some inline requests for changes.

2021-12-01 21:17 UTC, kwf37 commented on redux/store.ts
> +            // if (
Can delete since we're moving this stuff to local storage

2021-12-01 21:17 UTC, kwf37 commented on services/auth.helper.ts
> + * Stores logged in user id
I think these comments should be a bit more detailed so they're more friendly to someone new to the project. I'm happy to take a look and try editing them as well.

2021-12-01 21:17 UTC, kwf37 commented on services/httpClient.ts
> + * Makes a 'GET' request
Should add notes about the auth side effects of this function.

2021-12-01 21:17 UTC, kwf37 commented on services/auth.helper.ts
> +const storageKey = 'exp-trk';
Maybe add a Constants comment banner and Export Functions comment banner. We've been copying our comment banners to all our new files

2021-12-01 21:17 UTC, kwf37 commented on services/httpClient.ts
> +
ditto on Constants and Functions comment banner.

2021-12-02 01:32 UTC, edward93 commented on services/httpClient.ts
> +
Done. I think :)

2021-12-02 01:33 UTC, edward93 commented on services/auth.helper.ts
> +const storageKey = 'exp-trk';
done

2021-12-02 01:33 UTC, edward93 commented on services/httpClient.ts
> + * Makes a 'GET' request
I added few more lines but I feel like I'm not quite covering everything. If you could tell me a bit more perhaps I could improve it

2021-12-02 01:34 UTC, edward93 commented on services/auth.helper.ts
> + * Stores logged in user id
Same as the bellow one

2021-12-02 01:34 UTC, edward93 commented on redux/store.ts
> +            // if (
done

2021-12-02 01:34 UTC, edward93 commented on pages/_app.tsx
> +export default dynamic(() => Promise.resolve(wrapper.withRedux(MyApp)), {
done

2021-12-02 18:52 UTC, kwf37 approved these changes
Looks good enough for now! I'm gonna post a minor issue to remind me about those eslint no-explicit any waivers cause I think we might wanna make those nicer later.

2021-12-02 19:10 UTC, merged